### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by zacharyw** [k-yle/pdf-to-img#242]
I'm attempting to use the pdf-to-img package in a [Remix ](https://remix.run/) application.

The package installs fine, and I'm able to import it, but the moment this function call exists:
```
const pdfDocument = await pdf(pdfBuffer);
```

I get the `ReferenceError: document is not defined` error. To be clear the `pdf` function doesn't need to be called at runtime: simply having it exist causes the error, and removing the call fixes it.

It's almost as though adding this function call somewhere breaks SSR somehow, though the error itself does not come out of this package. It makes me wonder if this package is doing something that causes side effects that break SSR.

Here's the full stack trace for the error:
```
ReferenceError: document is not defined
    at $431fbd86ca7dc216$export$b204af158042fbac (file:///workspaces/lit-lineup/node_modules/@react-aria/utils/dist/domHelpers.mjs:3:154)
    at $431fbd86ca7dc216$export$f21a1ffae260145a (file:///workspaces/lit-lineup/node_modules/@react-aria/utils/dist/domHelpers.mjs:7:17)
    at $507fabe10e71c6fb$var$setupGlobalFocusEvents (file:///workspaces/lit-lineup/node_modules/@react-aria/interactions/dist/useFocusVisible.mjs:84:114)
    at $507fabe10e71c6fb$export$ec71b4b83ac08ec3 (file:///workspaces/lit-lineup/node_modules/@react-aria/interactions/dist/useFocusVisible.mjs:221:5)
    at $f7dceffc5ad7768b$export$4e328f61c538687f (file:///workspaces/lit-lineup/node_modules/@react-aria/focus/dist/useFocusRing.mjs:22:40)
    at v (file:///workspaces/lit-lineup/node_modules/@headlessui/react/dist/components/button/button.js:1:477)
    at renderWithHooks (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:5724:16)
    at renderForwardRef (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:5919:18)
    at renderElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6082:11)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderNode (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6336:12)
    at renderChildrenArray (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6288:7)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6218:7)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderNode (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6336:12)
    at renderHostElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:5708:3)
    at renderElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderForwardRef (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:5936:5)
    at renderElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6082:11)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderNode (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6336:12)
    at renderHostElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:5708:3)
    at renderElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderNode (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6336:12)
    at renderChildrenArray (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6288:7)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6218:7)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderNode (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6336:12)
    at renderHostElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:5708:3)
    at renderElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderNode (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6336:12)
    at renderChildrenArray (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6288:7)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6218:7)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderNode (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6336:12)
    at renderHostElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:5708:3)
    at renderElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:5852:7)
    at renderElement (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (/workspaces/lit-lineup/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
```

**Comment by k-yle** [comment]
I've never encountered this before, perhaps you could try adding this snippet _before_ the import statement, to see what code is trying to access `document`:

```js
globalThis.document = new Proxy({}, { get: console.trace, set: console.trace })
```

**Comment by shurth** [comment]
FWIW, this happens in Nuxt 3 as well. Just spent an hour tracking it down to this library. I'm attempting to use it in a Nuxt server api endpoint (server directory) and my app won't load as long as there's a call to the "pdf" function anywhere in my code.
